services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      BACKEND_PORT: "${BACKEND_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: pnpm --filter @ultramed/api dev

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:${BACKEND_PORT}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter @ultramed/web dev

volumes:
  mysql_data_dev:
