services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ultramed
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/ultramed"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: pnpm --filter @ultramed/api dev

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter @ultramed/web dev

volumes:
  mysql_data_dev:
