services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - mysql_data_prod:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      BACKEND_PORT: "${BACKEND_PORT}"
    depends_on:
      - db
    restart: always

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      NEXT_PUBLIC_API_URL: "https://api.ultramed.az" # Change to actual domain
      FRONTEND_PORT: "${FRONTEND_PORT}"
    restart: always

volumes:
  mysql_data_prod:
